### ISSUE TITLE
exec_jwst_level3_register_and_combine_miri_example association table formatting

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/da5-notebooks#16]
Just a suggestion...

The  ASN table given in section two could be made more readable by running through a YAML beautifier like https://jsonformatter.org/yaml-formatter. 

```
asn_type: None
asn_rule: DMS_Level3_Base
version_id: null
code_version: 0.10.1a.dev241
degraded_status: 'No known degraded exposures in association.'
program: noprogram
constraints: 'No constraints'
asn_id: a3001
target: none
asn_pool: none
products:
    -
        name: jw10002_short
        members:
            - {expname: jw10002001001_01101_00001_nrcb1_cal.fits, exptype: science}
            - {expname: jw10002001001_01101_00001_nrcb2_cal.fits, exptype: science}
            - {expname: jw10002001001_01101_00001_nrcb3_cal.fits, exptype: science}
            - {expname: jw10002001001_01101_00001_nrcb4_cal.fits, exptype: science}
            - {expname: jw10002001001_01102_00001_nrcb1_cal.fits, exptype: science}
            - {expname: jw10002001001_01102_00001_nrcb2_cal.fits, exptype: science}
            - {expname: jw10002001001_01102_00001_nrcb3_cal.fits, exptype: science}
            - {expname: jw10002001001_01102_00001_nrcb4_cal.fits, exptype: science}
```
